apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: redis
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data
    server: redisfs-1-vm
    readOnly: false
