apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-volume
  namespace: redis
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-ssd
  fstype: ext4
volumeBindingMode: WaitForFirstConsumer
